# Generated by Django 5.0 on 2023-12-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('blockid', models.AutoField(primary_key=True, serialize=False)),
                ('blockname', models.CharField(max_length=255)),
                ('noofrooms', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostelid', models.AutoField(primary_key=True, serialize=False)),
                ('hostelname', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('num_of_beds', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('roomtypeid', models.AutoField(primary_key=True, serialize=False)),
                ('typename', models.CharField(max_length=255)),
            ],
        ),
    ]
