# Generated by Django 5.0 on 2023-12-08 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosteldetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomid', models.AutoField(primary_key=True, serialize=False)),
                ('roomname', models.CharField(max_length=255)),
                ('facilities', models.TextField()),
                ('noofbeds', models.PositiveIntegerField()),
                ('blockid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosteldetails.block')),
                ('roomtypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosteldetails.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='BedDetails',
            fields=[
                ('bedid', models.AutoField(primary_key=True, serialize=False)),
                ('bedname', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosteldetails.room')),
            ],
        ),
    ]
