# Generated by Django 5.0 on 2023-12-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosteldetails', '0002_room_beddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='beddetails',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
