# Generated by Django 5.0 on 2023-12-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosteldetails', '0004_hostel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='image',
        ),
    ]
