# Generated by Django 5.0 on 2023-12-29 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosteldetails', '0005_remove_hostel_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='hostelid',
        ),
        migrations.AddField(
            model_name='hostel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_images/'),
        ),
        migrations.AlterField(
            model_name='beddetails',
            name='bedid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='email',
            field=models.EmailField(max_length=23),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='num_of_beds',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='RoomVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('purpose', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosteldetails.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
