# Generated by Django 5.0 on 2024-01-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosteldetails', '0006_remove_hostel_hostelid_hostel_id_hostel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelname', models.TextField()),
                ('address', models.TextField()),
                ('district', models.TextField()),
            ],
        ),
    ]
