# Generated by Django 5.0 on 2023-12-08 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosteldetails', '0003_beddetails_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.AutoField(primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('customercategory', models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('chid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('onotes', models.CharField(max_length=200)),
                ('towncity', models.CharField(max_length=100)),
                ('postcodezip', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('checkoutdate', models.DateTimeField(default='2023-10-30')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('vacate_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosteldetails.beddetails')),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pmid', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(default='5001', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('expiry_month', models.CharField(max_length=2)),
                ('expiry_year', models.CharField(max_length=2)),
                ('cvv', models.CharField(max_length=3)),
                ('paymentdate', models.DateTimeField(default='2023-10-30')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.customer')),
            ],
        ),
    ]
