# Generated by Django 5.0 on 2024-01-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosteldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=100)),
                ('licence_number', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('dormitory', 'Dormitory')], max_length=20)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
